# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Catstagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Catstagram
  pod 'Alamofire'
  target 'CatstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatstagramUITests' do
    # Pods for testing
  end

end
